refactor: change the parsing target and method
NTUST-Tool/Course_order_suggestion_system pull request #63
Opened 2024-12-23 07:11 UTC by liang36176381

改為讀取初選登記頁面的登記志願清單，可以避免顯示預先加入課表的必修

2024-12-24 02:59 UTC, jeffpeng3 commented
你好
感謝你的PR
以下幾點想跟你討論一下

在一開始設計時，有考慮到有些人會根據選課比率決定要不要加入戰爭，所以regex的部分，而我個人在測試時，也是使用課程查詢去測試的。

這個功能在Dcard上有被提及，我也在思考應該怎麼實現，看了你的實現之後茅塞頓開，但這樣的修改也會讓使用情境侷限在初選清單。

我個人希望是在不影響原本使用性的前提下增加功能，若是找到selector就過濾，否則全文regex match。

不知道你對此有什麼看法？

2024-12-24 06:12 UTC, liang36176381 commented
你好，感謝你的建議，這是我的疏忽，確實如你所說，這個 PR 讓功能的使用情境侷限於初選，應該在不影響原先功能的前提下做擴展。

你提到的「先嘗試尋找 selector，如果失敗則退回全文 regex match」，我認為這是一個很好的方法，可以先以這個方法實作。
不過我目前還有個想法，想和你討論其可行性：

改回處理選課清單頁面，仍然以全文 regex match作為第一步，提取所有課程代碼。
接下來嘗試提取頁面中的系級資訊，並組合出對應的 EduCode，通過 /querycourse/api/CourseSchedule 查詢班級課表。
從查詢到的班級課表中篩選出必修課，並將這些必修課從全文 regex 匹配出的課程代碼列表中移除。這樣應該可以有效排除（除了體育課以外）預先加入課表的系必修課程。

不過，我發現這個方法目前仍有一些問題：
1. 大一的班級課表中包含國文和英文課，但這些課程是需要選的。
2. 其他系級的情況我不確定，但在資工的班級課表中，有「台灣電資產業論壇與工程倫理」和「電資概論與工程倫理」這個必修課是需要選課的。
因此，我對這個方法的可行性還有些疑問。希望能聽聽你的看法，或者有其他建議的處理方式。

2024-12-24 07:39 UTC, jeffpeng3 commented
我們電子系的話，有**物理**這類多個老師選一個的必修課，跟大一國文同個概念，也是考慮到有這類課程，所以我當初就捨棄班級課表的做法了，也因此看到這個需求的時候思考了許久遲遲沒有動手。
![image](https://github.com/user-attachments/assets/e4760cb8-1c6a-4d00-bf1a-3e297765d460)

我是覺得應該沒有更乾淨的實作了，不然就要看看還有沒有其他人有點子了

2024-12-24 10:14 UTC, liang36176381 commented
那這樣應該ok了，同時支持原先的全局regex match及selector

2024-12-24 13:39 UTC, jeffpeng3 commented
看起來差不多了
有發現幾個疑問的點再麻煩回覆

2024-12-25 13:11 UTC, liang36176381 commented
還有任何問題的話都可以提

2024-12-25 14:04 UTC, jeffpeng3 commented
review那個部分麻煩了

2024-12-25 16:08 UTC, liang36176381 commented
我這邊沒有看到新的review comment，是我誤會或是漏掉了些什麼嗎

2024-12-25 17:22 UTC, jeffpeng3 requested changes
抱歉忘了按下submit
太久沒用這功能了...

2024-12-25 17:22 UTC, jeffpeng3 commented on src/main.rs
> +        fetch_all_courses(course_ids.iter().map(|s| s.as_str()).collect(), &client, &semester).await;
想了解一下這裡為什麼需要這樣改

2024-12-25 17:22 UTC, jeffpeng3 commented on src/main.rs
> +            .map(|m| m.as_str().to_string())
這裡是否可以as_str就好
不用to_string
這樣下面應該就不用再轉換一次了？

2024-12-26 03:36 UTC, liang36176381 commented on src/main.rs
> +            .map(|m| m.as_str().to_string())
如果在找到 selector 後只用 as_str 轉成 Vec<&str>，這些&str 參考的是 table_html，但 table_html 會在離開 extract_course_ids 時被釋放，造成這些 &str 指向被釋放的記憶體

對 file_content 而言，因為它是從 main 傳入，理論上能活到 main 結束，所以只用 as_str() 參照也不太會出問題(應該?)
不過為了與上面的回傳保持一致，這裡也一併轉為 String

2024-12-26 03:37 UTC, liang36176381 commented on src/main.rs
> +        fetch_all_courses(course_ids.iter().map(|s| s.as_str()).collect(), &client, &semester).await;
把 extract_course_ids 回傳的 Vec<String> 轉成 fetch_all_courses 要的 Vec<&str>

2024-12-26 08:28 UTC, jeffpeng3 commented on src/main.rs
> +            .map(|m| m.as_str().to_string())
了解
被python寵壞了
對這語言的生命週期管理實在是不熟悉
那這個沒問題了

2024-12-26 08:39 UTC, jeffpeng3 commented on src/main.rs
> +        fetch_all_courses(course_ids.iter().map(|s| s.as_str()).collect(), &client, &semester).await;
我做了一些修改
我自行測試時也是能運作的
而且code比較簡潔
再麻煩你檢查一下這個修改有沒有問題
沒有的話加上去應該就可以合併了

```diff
diff --git a/src/main.rs b/src/main.rs
index 9372009..e63c3b3 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -138,7 +138,7 @@ fn get_process_bar(count: usize) -> impl BarExt {
 async fn get_course_info(
     client: &Client,
     semester: &str,
-    course_id: &str,
+    course_id: String,
 ) -> Result<Course, Box<dyn Error>> {
     let url = "https://querycourse.ntust.edu.tw/querycourse/api/courses";
     let body = json!({
@@ -180,7 +180,7 @@ async fn get_semester(client: &Client) -> Result<String, reqwest::Error> {
 }
 
 async fn fetch_all_courses(
-    course_ids: Vec<&str>,
+    course_ids: Vec<String>,
     client: &Client,
     semester: &str,
 ) -> (Vec<Course>, Vec<Course>, Vec<String>) {
@@ -226,7 +226,7 @@ async fn main() {
     let semester = get_semester(&client).await.wrap_or_exit("無法取得學期資訊");
 
     let (mut safe_courses, mut unsafe_courses, unknown_courses) =
-        fetch_all_courses(course_ids.iter().map(|s| s.as_str()).collect(), &client, &semester).await;
+        fetch_all_courses(course_ids, &client, &semester).await;
 
     for course in unknown_courses {
         eprint!("\n警告: 查無課程資料，課程代碼: {}", course);
```

2024-12-26 11:31 UTC, liang36176381 commented on src/main.rs
> +        fetch_all_courses(course_ids.iter().map(|s| s.as_str()).collect(), &client, &semester).await;
這樣改沒有問題，我原本想說這兩個function裡面只做簡單讀取，所以&str比較輕量
不過這份專案中這點複製成本基本可以忽略，這樣 code 也比較簡潔

2024-12-26 13:15 UTC, jeffpeng3 commented on src/main.rs
> +        fetch_all_courses(course_ids.iter().map(|s| s.as_str()).collect(), &client, &semester).await;
我不熟悉rust的特性
這個Vec作為參數傳進去應該不會複製？
那這種作法應該比較省運算吧
不會透過collect複製出一個完整的Vec？

2024-12-26 14:42 UTC, liang36176381 commented on src/main.rs
> +        fetch_all_courses(course_ids.iter().map(|s| s.as_str()).collect(), &client, &semester).await;
不會複製 我在搞，rust只會移交所有權，這樣是最省運算的了

2024-12-26 15:28 UTC, jeffpeng3 commented on src/main.rs
> +        fetch_all_courses(course_ids.iter().map(|s| s.as_str()).collect(), &client, &semester).await;
OK
那應該就沒問題了

2024-12-26 15:28 UTC, jeffpeng3 approved these changes

2024-12-26 15:29 UTC, merged

2024-12-26 15:30 UTC, jeffpeng3 commented
感謝你的PR!
我這幾天再找時間Release